apiVersion: v1
kind: Service
metadata:
  name: nlp-inference-service
  namespace: staging
spec:
  selector:
    app: nlp-inference
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
